---
title: "STAT 184 Final Project: Exploratory Data Analysis"
output: html_notebook
author: "Jordan Williard"
date: "April 7th, 2020"
---

# Guiding Question (i.e., Research Question): Make a clear statement of a single guiding/research question that will drive your analysis.  It should be phrased as a question that you will try to investigate (i.e., it should have a question mark) 

How has the landscape of American political ideology changed throughout the past 100 years? Which states have experienced the most change? Are there any notable long term trends?

# Become acquainted with your data sources:
* Where did you find them?

    Data Source 1: Comparative Political Dataset (https://www.cpds-data.org/). I found this by searching and comparing various political datasets. 
  
    Data Source 2: US Population by Zip Code (https://data.world/lukewhyte/us-population-by-zip-code-2010-2016. I want to include demographic data in this analysis. This             dataset has a good cross section of years leading up to present day politics. 

* Who collected/maintains them?
    
    Data Source 1 is maintained by Prof. Dr. Klaus Armingeon and collaborators at the University of Zurich. 
    
    Data Source 2 was aggregated by a user on data.world. The data comes from 5-year American Surveys and the 2010 Decennial Census

* When & Why were they originally collected?
    
    The data in Data Source 1, the CPDS, has been collected since 1960 in many democratic countries. The goal is to better understand the political landscape of democratic       countries across the globe. I'll be focusing on the United States. 
    
    The data in Data Source 2 has been collected by the United States government for demographic purposes. These surveys allow the government to better understand who and        where people are living. 

* What does a case represent in each data source, and how many total cases are available?

* What are some of the variables that you plan to use

* The R Notebook should include R code chunks & output as well as narrative (bullet list is fine at this stage) as you answer these questions

# Explore intuition related to the research question
* Create some informative plots and summary statistics 

* Describe preliminary observations and intuition about the research question

# TWO Data Sources (at least)
* Primary data:  This is the main data source to be used in your investigation and it MUST NOT be loaded directly from an R package (but API's are fine for example). You should have many cases (e.g., at least hundreds--preferably many thousands), many variables including a mixture of both categorical & quantitative variables.  

* Other data sources: No problem for these to come from an R package--for example, the ZipGeography or ZipDemography data (from DataComputing package) might be useful when joined with primary sources as you investigate some phenomenon in the US. 

* Note: Each data source should be less than 80-100MB--the maximum file size permitted in a GitHub Repo... use sampling to create a reduced version for the purpose of the project if needed as we've done occasionally in exercises and weekly activities.